apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-server
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-server-container
          image: nginx:latest
          ports:
            - containerPort: 80
