apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-server
  labels:
    app: tomcat
  namespace: test
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      name: tomcat-server
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat-server
          image: tomcat:7.0
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /    
              port: 8080
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /
              port: 8080
