apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-server
  labels:
    app: tomcat
  annotations:
    kubernetes.io/change-cause: version 9.0
  namespace: test
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      name: tomcat-server
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat-server
          image: tomcat:9.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 300Mi
