apiVersion: v1
kind: Service
metadata:
  name: nginx-server-service
  labels:
    app: nginx
  namespace: test
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30088
