apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  labels:
    app: server
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-server
      labels:
        app: server
    spec:
      containers:
        - name: nginx-server
          image: seoulbigdata-registry.ncr.gov-ntruss.com/nginx:test
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ncp-registry-key
      nodeSelector:
        key: prod
