apiVersion: v1
kind: Service
metadata:
  name: tomcat-server-service
  labels:
    app: tomcat
  namespace: test
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
      nodePort: 30088
