apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-server
  labels:
    app: tomcat
  annotations:
    kubernetes.io/change-cause: version 8.7
  namespace: test
spec:
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      name: tomcat-server
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat-server
          image: tomcat:8.7
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 300Mi
          volumeMounts:
            - mountPath: "/prod/web-portal"
              name: prod-nas
          livenessProbe:
            exec:
              command: ["cat", "/prod/web-portal/ready.txt"]
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /
              port: 8080
      volumes:
        - name: prod-nas
          persistentVolumeClaim:
            claimName: prod-nas
